language: go
sudo: false
go:
- '1.10'
- tip
services:
- docker
before_install:
- go get -t -v ./...
script:
- go test ./... -race -coverprofile=coverage.txt -covermode=atomic
after_success:
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- scripts/build.sh
deploy:
- provider: releases
  api_key:
    secure: arHqANKbYa42uYZaCtkWH45TIkDJatsjuXtuHAOYokObFQGFrU+K3NEHXS+HFFL0yxbHmAKL/dgS8hqXJSfZjE7SI9hIBXFcYDE3Xily5ogzfEdCKFo5W0V5vwwP+Exie6kheoxYe5Gpq40hk4v92nH+IFwaPf6T/GGIJeqAtkltzWmF3f3WTHr/ZEblNX2O1WQTA42WEsm4p6hXjdqnbPyMJHlwy54ytf+cN+X5+OYW3h8l5/9NNVF91y0FLmwRFuF79UbXjjTz4Hud+KhheSOxKSZYQBplYRLvdstkhRIJB9IzLUzHdb1bKS4IDAigNip2PBBJhvfwguVx6KOmeXhpwmrthCkmOFBEbZ8t2OKXfA3B9SWsaim96l4fVEcygDQR0Be5tp9az+P8mAKbuFa2lBD4yhJCSRKREjdVKF09AJ2Gl3zdxh4VlpQcAeUAiMIsDwMBDYbn0RjFtq7mTvnviZs73aplPDRvDZv/nOdS7aI7hBjt2upq7FD9jSiSau5gkAyAywYDQEUUqDj5JYJsGVRWjBFvo20VuBNWIT12j3Y+PfRGHe+3fjKlHaHZkeKsVCd0R3CKDJfeE8wVlm2LTWuuJGlqgdXXsyc1UDNJRBR4M971AamjeX9KoD7ORFD3LYocUITb9Rlb+Xab/RX05u1idKMJUauTKEjJn9E=
  file:
  - goron-linux-amd64
  - goron-linux-386
  - goron-darwin
  - goron-windows
  skip_cleanup: true
  on:
    tags: true
- provider: script
  script: scripts/deploy.sh
  skip_cleanup: true
  on:
    tags: true
